# Generated by Django 5.2.5 on 2025-08-17 06:30
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

	dependencies = [
		('documents', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='article',
			name='attachment',
			field=models.FileField(blank=True, null=True, upload_to=documents.models.upload_to_article, verbose_name='Вложение (PDF)'),
		),
	]